<div class="row justify-content-md-center">
    <div class="col col-7">
        <?php if ($error && $error instanceof \Exception): ?>
            <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading"><?= $error->getMessage(); ?></h4>
                <?php if ($error->getPrevious()): ?>
                <p>There is more information in previous exceptions:</p>
                <ul>
                <?php while (($error = $error->getPrevious())): ?>
                    <li><?= $error->getMessage(); ?></li>
                <?php endwhile; ?>
                </ul>
                <?php endif; ?>
            </div>
        <?php else: ?>
            <ul class="list-unstyled">
                <?php foreach ($users as $key => $user): ?>
                <li class="media my-4 user-container <?= ($key > 99) ? 'd-none' : '' ?>">
                    <?php if ($user->getAvatar()): ?>
                        <img style="width:64px" src="<?= $user->getAvatar(); ?>" class="mr-3 user-avatar" alt="avatar" />
                    <?php else: ?>
                        <img style="width:64px" src="/img/noavatar.png" class="mr-3 user-avatar" alt="avatar" />
                    <?php endif; ?>
                    <div class="media-body">
                        <h5>
                            <a class="user-name" href="#<?= $user->getUuid(); ?>" title="Click for details"><?= $user->getName(); ?></a>
                        </h5>
                        <span class="user-title"><?= $user->getTitle(); ?></span> at <span class="user-company"><?= $user->getCompany(); ?></span>
                            <div class="text-muted user-bio" data-full="<?= $user->getBio(); ?>">
                            <?php if ($user->getBio()): ?>
                                <?= mb_substr($user->getBio(), 0, 64); ?>...
                            <?php endif; ?>
                            </div>
                    </div>
                </li>
                <?php endforeach; ?>
            </ul>
            <?php if (count($users) > 10): ?>
                <div class="row justify-content-md-center">
                    <div class="col col-4">
                        <button type="button" class="btn btn-primary" id="showMoreBtn">Show more</button>
                    </div>
                </div>
                <script>
                    let userContainers = $('.user-container');
                    let currentShown = 100;
                    const showAmount = 100;
                    $('#showMoreBtn').click(function() {
                        let last = currentShown + showAmount;
                        if (last > userContainers.length) {
                            last = userContainers.length;                            
                        }
                        for (let i = currentShown; i < last; i++) {
                            userContainers[i].classList.remove('d-none');
                        }
                        currentShown = last;
                        if (last == userContainers.length) {
                            this.disabled = "disabled";
                            this.classList.remove('btn-primary');
                            this.classList.add('btn-secondary');
                            this.innerHTML = 'No more results';
                        }
                    });
                </script>
            <?php endif; ?>
            <div class="modal" tabindex="-1" role="dialog" id="detailsModal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">User Details</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-2">
                                    <img src="#" alt="detailed avatar" style="width:64px" id="detailsAvatar" />
                                </div>
                                <div class="col-10">
                                    <h5 id="detailsName"></h5>
                                    <h6 id="detailsPosition" class="text-muted"></h6>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col" id="detailsBio"></div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                let detailsModal = $('#detailsModal');
                $('.user-name').click(function(e) {
                    e.preventDefault();
                    let userContainer = $(this).parents('.user-container')[0];
                    let avatar = userContainer.querySelector('.user-avatar').src;
                    let name = userContainer.querySelector('.user-name').innerHTML;
                    let title = userContainer.querySelector('.user-title').innerHTML;
                    let company = userContainer.querySelector('.user-company').innerHTML;
                    let bio = userContainer.querySelector('.user-bio').dataset.full;
                    detailsModal.find('#detailsAvatar')[0].src = avatar;
                    detailsModal.find('#detailsName')[0].innerHTML = name;
                    detailsModal.find('#detailsPosition')[0].innerHTML = title + ' at ' + company;
                    detailsModal.find('#detailsBio')[0].innerHTML = bio;
                    detailsModal.modal('show');
                });
            </script>
        <?php endif; ?>
    </div>
</div>
