<div class="row justify-content-md-center">

    <div class="col col-6">

        <ul class="list-unstyled">

            <?php for ($i=0; $i < 15; $i++): ?>
            <li class="media my-4">
                <img style="max-width:64px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnH4Yu8_WWhN8RVxzE-JAmGE2cy6MlB7fqOZBwiJj8DAAndpR4" class="mr-3" alt="avatar" />
                <div class="media-body">
                    <h5><a href="#">Willis Yost</a></h5>
                    Precision Instrument Repairer at Harris, Greenfelder and Thompson
                    <div class="text-muted">Temporibus doloremque molestiae odio qui velit magnam voluptates. Sit sapiente esse consequatur illo. Ut quo modi molestiae aperiam eius.</div>
                </div>
            </li>
            <?php endfor; ?>
        </ul>

    </div>

</div>
